# 行人数据集

##  pixel_pos.csv文件格式

pixel_pose.csv包含4行，第一行是所有的Frame Number；第二行是所有行人的ID；第三行是所有的y坐标；第四行是所有的x坐标。

pixel_pose.csv的列数是所有行人轨迹点的数量。

In [12]:
import os
import numpy as np

directory = "./data/eth/hotel"

file_path = os.path.join(directory, 'pixel_pos.csv')

data = np.genfromtxt(file_path, delimiter=',')

# Get the number of pedestrians in the current dataset
numPeds = np.size(np.unique(data[1, :]))

print("number of pedestrians is:".format(numPeds))

traj = data[:, data[1, :] == 2]

print("traj of pedestrians 1 is:")
print(traj)

traj = traj[[3, 2, 0], :]

print("format traj:")
print(traj)

number of pedestrians is:
traj of pedestrians 1 is:
[[ 1.      11.     ]
 [ 2.       2.     ]
 [ 0.55382  0.56076]
 [ 0.21944  0.175  ]]
format traj:
[[ 0.21944  0.175  ]
 [ 0.55382  0.56076]
 [ 1.      11.     ]]


In [13]:
import tensorflow as tf

batch_size = 3
sentence_max_length = 5
n_features = 2
new_shape = (batch_size, sentence_max_length, n_features)
x = tf.constant(np.reshape(np.arange(30), new_shape), dtype = tf.float32)

print(x)

inputs = tf.split(x, sentence_max_length, 1)

print(inputs)

inputs = [tf.squeeze(input_, [1]) for input_ in inputs]

print(inputs)

tf.Tensor(
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]
  [ 8.  9.]]

 [[10. 11.]
  [12. 13.]
  [14. 15.]
  [16. 17.]
  [18. 19.]]

 [[20. 21.]
  [22. 23.]
  [24. 25.]
  [26. 27.]
  [28. 29.]]], shape=(3, 5, 2), dtype=float32)
[<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 0.,  1.]],

       [[10., 11.]],

       [[20., 21.]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 2.,  3.]],

       [[12., 13.]],

       [[22., 23.]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 4.,  5.]],

       [[14., 15.]],

       [[24., 25.]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 6.,  7.]],

       [[16., 17.]],

       [[26., 27.]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[ 8.,  9.]],

       [[18., 19.]],

       [[28., 29.]]], dtype=float32)>]
[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [10., 11.],
       [20.,